### ISSUE TITLE
[EPIC] Keycloakify

### ISSUE THREAD

**Issue by AdamRaven** [truzzt/truzzt-keycloak-themes#15]
- [ ] Keycloakify design Email Templates
- [ ] Keycloakify design Logout Page
- [ ] Keycloakify design Settings Page
- [ ] Keycloakify design OTP Page
- [ ] Keycloakify design Login Page
- [ ] Write documentation to Keycloakify
- [ ] Keycloakify design Register Page
- [ ] Keycloakify design Password Reset Page
- [ ] Keycloakify design Forgot Password Page
- [ ] Keycloakify setup CI
- [ ] Keycloakify open repository
